name: VoxelPort
main: com.thevoxelbox.voxelport.VoxelPort
version: 2.049
website: http://www.voxelwiki.com/minecraft/index.php/VoxelPort
author: przerwap
description: >
             Simulates real world travel.
commands:
  vworld:
    description: Check your current world.
    usage: |
           /<command>
           Example: /<command> - need to write the help.
  ctime:
    description: Check the time, in ticks, of your current world.
    usage: |
           /<command>
           Example: /<command> - need to write the help.
  vp:
    description: The main VoxelPort command.
    usage: |
           /<command>
           Example: /<command> - need to write the help.